export enum CharacterName {
  BRIMSTONE = "brimstone",
  PHOENIX = "phoenix",
  Sage = "sage",
  SOVA = "sova",
  VIPER = "viper",
  CYPHER = "cypher",
  REYNA = "reyna",
  KILLJOY = "killjoy",
  BREACH = "breach",
  OMEN = "omen",
  JETT = "jett",
  RAZE = "raze",
  SKYE = "skye",
  YORU = "yoru",
  ASTRA = "astra",
  KAYO = "kayo",
  CHAMBER = "chamber",
  NEON = "neon",
  FADE = "fade",
  HARBOR = "harbor",
  GEKKO = "gekko",
}
